---
id: tqrk08
base_name: hypermicrodata-client
tags:
  - ruby
  - tqrk08
presentation_date: 2014-11-29
version: 2014.11.29.1
licenses:
  - CC BY-SA 4.0
slideshare_id: tqrk08-hypermicrodataclient
speaker_deck_id: hypermicrodata-client
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Kunihiko Ito
  email: kuni.110.92@gmail.com
  rubygems_user: kunitoo
  slideshare_user: kunitoo
  speaker_deck_user: kunitoo
